export const lists = [
  { name: 'London', 月份: 'Jan.', 月均降雨量: 18.9 },
  { name: 'London', 月份: 'Feb.', 月均降雨量: 28.8 },
  { name: 'London', 月份: 'Mar.', 月均降雨量: 39.3 },
  { name: 'London', 月份: 'Apr.', 月均降雨量: 81.4 },
  { name: 'London', 月份: 'May', 月均降雨量: 47 },
  { name: 'London', 月份: 'Jun.', 月均降雨量: 20.3 },
  { name: 'London', 月份: 'Jul.', 月均降雨量: 24 },
  { name: 'London', 月份: 'Aug.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug1.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug2.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug3.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug4.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug5.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug15.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug25.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug35.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug45.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug55.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug65.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug115.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug225.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug335.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug445.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug555.', 月均降雨量: 35.6 },
  { name: 'London', 月份: 'Aug665.', 月均降雨量: 35.6 },
  { name: 'Berlin', 月份: 'Mar.', 月均降雨量: 34.5 },
  { name: 'Berlin', 月份: 'Apr.', 月均降雨量: 99.7 },
  { name: 'Berlin', 月份: 'May', 月均降雨量: 52.6 },
  { name: 'Berlin', 月份: 'Jun.', 月均降雨量: 35.5 },
  { name: 'Berlin', 月份: 'Jul.', 月均降雨量: 37.4 },
  { name: 'Berlin', 月份: 'Aug.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug1.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug2.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug3.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug4.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug5.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug15.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug25.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug35.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug45.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug55.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug65.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug115.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug225.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug335.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug445.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug555.', 月均降雨量: 42.4 },
  { name: 'Berlin', 月份: 'Aug665.', 月均降雨量: 42.4 }
]

export const lists2 = [
  { name: 'London', 月份: 'Jan.', 月均降雨量: 18.9 },
  { name: 'London', 月份: 'Feb.', 月均降雨量: 28.8 },
  // { name: 'London', 月份: 'Mar.', 月均降雨量: 39.3 },
  // { name: 'London', 月份: 'Apr.', 月均降雨量: 81.4 },
  // { name: 'London', 月份: 'May', 月均降雨量: 47 },
  // { name: 'London', 月份: 'Jun.', 月均降雨量: 20.3 },
  // { name: 'London', 月份: 'Jul.', 月均降雨量: 24 },
  // { name: 'London', 月份: 'Aug.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug1.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug2.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug3.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug4.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug5.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug15.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug25.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug35.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug45.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug55.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug65.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug115.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug225.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug335.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug445.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug555.', 月均降雨量: 35.6 },
  // { name: 'London', 月份: 'Aug665.', 月均降雨量: 35.6 },

  { name: 'Berlin', 月份: 'Jan.', 月均降雨量: 12.4 },
  { name: 'Berlin', 月份: 'Feb.', 月均降雨量: 23.2 },
  // { name: 'Berlin', 月份: 'Mar.', 月均降雨量: 34.5 },
  // { name: 'Berlin', 月份: 'Apr.', 月均降雨量: 99.7 },
  // { name: 'Berlin', 月份: 'May', 月均降雨量: 52.6 },
  // { name: 'Berlin', 月份: 'Jun.', 月均降雨量: 35.5 },
  // { name: 'Berlin', 月份: 'Jul.', 月均降雨量: 37.4 },
  // { name: 'Berlin', 月份: 'Aug.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug1.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug2.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug3.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug4.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug5.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug15.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug25.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug35.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug45.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug55.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug65.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug115.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug225.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug335.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug445.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug555.', 月均降雨量: 42.4 },
  // { name: 'Berlin', 月份: 'Aug665.', 月均降雨量: 42.4 }

  { name: 'London', 月份: 'Mar.', 月均降雨量: 39.3 },
  { name: 'London', 月份: 'Apr.', 月均降雨量: 81.4 },
  { name: 'Berlin', 月份: 'Mar.', 月均降雨量: 34.5 },
  { name: 'Berlin', 月份: 'Apr.', 月均降雨量: 99.7 }
]
